apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  annotations:
    deployOVS: 'false'
  namespace: openshift-cnv
spec:
  enableCommonBootImageImport: true
  virtualMachineOptions:
    disableFreePageReporting: false
    disableSerialConsoleLog: false
  higherWorkloadDensity:
    memoryOvercommitPercentage: 150
  liveMigrationConfig:
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 1
    parallelOutboundMigrationsPerNode: 1
    progressTimeout: 150
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  enableApplicationAwareQuota: false
  infra: {}
  applicationAwareConfig:
    allowApplicationAwareClusterResourceQuota: false
    vmiCalcConfigName: DedicatedVirtualResources
  ksmConfiguration:
    nodeLabelSelector: {}
  evictionStrategy: LiveMigrateIfPossible
  featureGates:
    deployTektonTaskResources: false
    enableMultiArchBootImageImport: false
    withHostPassthroughCPU: false
    downwardMetrics: false
    disableMDevConfiguration: false
    declarativeHotplugVolumes: false
    deployKubeSecondaryDNS: false
    nonRoot: true
    alignCPUs: false
    enableManagedTenantQuota: false
    persistentReservation: false
    autoResourceLimits: true
    decentralizedLiveMigration: false
  workloadUpdateStrategy:
    batchEvictionInterval: 1m0s
    batchEvictionSize: 10
    workloadUpdateMethods:
      - LiveMigrate
      - Evict
  deployVmConsoleProxy: false
  uninstallStrategy: BlockUninstallIfWorkloadsExist
  workloads: {}
  resourceRequirements:
    vmiCPUAllocationRatio: 10