apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
  storageClassName: local-block
  volumeMode: Block
  deviceInclusionSpec:
    minSize: 400Gi
    deviceTypes:
      - disk