apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - lan-node-01
              - lan-node-02
              - lan-node-03
              - lan-node-04
              - lan-node-05
              - lan-node-06
  storageClassName: local-block
  volumeMode: Block
  deviceInclusionSpec:
    deviceTypes:
      - disk
    models:
      - 'RAID 930-8i-2GB'
      - 'PERC H730 Mini'