apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: dashy
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: dashy
  repo: https://vyrtualsynthese.github.io/selfhosted-helmcharts/