apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dmz-infrastructure
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/sigaint-au/sigaint-iac
      revision: HEAD
      directories:
      - path: infrastructure/openshift-cert-manager-operator/overlays/dmz/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/sigaint-au/sigaint-iac
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true