---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  ext-quay-db-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  refreshInterval: "1h"
  target:
    name: quay-db-app
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "quay-db-rw:5432:quay:quay:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://quay-db-rw.sigaint-quay:5432/app?password={{ .password }}}&user=quay"
        fqdn-jdbc-uri: "jdbc:postgresql://quay-db-rw.sigaint-quay.svc.cluster.local:5432/quay?password={{ .password }}&user=quay"
        uri: "postgresql://app:{{ .password }}@quay-db-rw.sigaint-quay:5432/quay"
  data:
    - secretKey: password
      remoteRef:
        key: QUAY_DB_PASSWORD