# quay-registry.yaml
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  configBundleSecret: quay-config-bundle
  components:
    - kind: clair
      managed: true
    - kind: postgres
      managed: false
    - kind: objectstorage
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: false
    - kind: route
      managed: false
    - kind: tls
      managed: false
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: quay
      managed: true
    - kind: clairpostgres
      managed: false
