---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-grafana-ldap
  namespace: sigaint-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: grafana-ldap
  data:
    - secretKey: ldap.toml
      remoteRef:
        key: GRAFANA_LDAP_TOML

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-grafana-ldap-certs
  namespace: sigaint-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: grafana-ldap-certs
  data:
    - secretKey: ca.crt
      remoteRef:
        key: LDAP_BIND_CA_CERT