---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: net-sigaint-dmz
  namespace: metallb-system
spec:
  addresses:
    - '10.120.20.100-10.120.20.150'
    - '2404:e80:4b6f:1:1337::1-2404:e80:4b6f:1:1337::100'
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: net-sigaint-vmnet
  namespace: metallb-system
spec:
  addresses:
    - '10.120.21.100-10.120.21.150'
    - '2404:e80:4b6f:6:1337::1-2404:e80:4b6f:6:1337::100'

  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: net-sigaint-wifi
  namespace: metallb-system
spec:
  addresses:
    - '10.120.13.60-10.120.13.100'
    - '2404:e80:4b6f:0:1337::1-2404:e80:4b6f:0:1337::100'
  autoAssign: true
  avoidBuggyIPs: false
