---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: net-sigaint-dmz
  namespace: metallb-system
spec:
  ipAddressPools:
    - net-sigaint-dmz
  interfaces:
    - br1.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: net-sigaint-vmnet
  namespace: metallb-system
spec:
  ipAddressPools:
    - net-sigaint-vmnet
  interfaces:
    - br1.21
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: net-sigaint-wifi
  namespace: metallb-system
spec:
  ipAddressPools:
    - net-sigaint-wifi
  interfaces:
    - br1.13