apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - ingres-tls.yaml
helmCharts:
- name: victoria-logs
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: victoria-logs-single
  repo: https://victoriametrics.github.io/helm-charts/