apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-tls.yaml
  - service.yaml
helmCharts:
  - name: victoria-logs-single
    version: 0.9.3
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: victoria-logs
    repo: https://victoriametrics.github.io/helm-charts/
