kind: Service
apiVersion: v1
metadata:
  name: victoria-logs-ingest
  namespace: sigaint-monitoring
spec:
  clusterIP: __PATCH__
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 9428
      targetPort: http

    - name: syslog-udp
      protocol: UDP
      port: 2514
      targetPort: 2514

    - name: syslog-tcp
      protocol: TCP
      port: 2514
      targetPort: 2514
  internalTrafficPolicy: Cluster
  clusterIPs:
    - __PATCH__
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: server