kind: Service
apiVersion: v1
metadata:
  name: victoria-logs-ingest
  annotations:
    metallb.io/ip-allocated-from-pool: net-sigaint-dmz
    metallb.universe.tf/address-pool: net-sigaint-dmz
spec:
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: syslog-tcp
      protocol: TCP
      port: 514
      targetPort: 2514
  internalTrafficPolicy: Cluster
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  sessionAffinity: None
  selector:
    app: server