apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# redhat-cop quay overlays stop at stable-3.11; pin latest channel locally.
resources:
  - https://github.com/redhat-cop/gitops-catalog/quay-operator/operator/base?ref=main
