apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # lhm-prod-dmz
  - lhm-prod-dmz/ext-sk-lhm-prod-admin.yaml
  - lhm-prod-dmz/ext-sk-lhm-prod-user.yaml
  # lhm-prod-vmnet
  - lhm-prod-vmnet/ext-sk-lhm-prod-admin.yaml
  - lhm-prod-vmnet/ext-sk-lhm-prod-user.yaml
