apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  # Sigaint DMZ
  - sigiant-dmz/sk-lan-local.yaml
  - sigiant-dmz/sk-yk-main.yaml

  # Sigaint VMNET
  - sigiant-vmnet/sk-lan-local.yaml
  - sigiant-vmnet/sk-yk-main.yaml
