kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: quay
spec:
  tls:
    - hosts:
        - __PATCH__
      secretName: quay-tls
  rules:
    - host: __PATCH__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quay-quay-app
                port:
                  name: http

