apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: victoria-logs-tls
  namespace: sigaint-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretName: victoria-logs-tls
  commonName: victoria.ocp.sigaint.au
  dnsNames:
    - victoria.ocp.sigaint.au
    - victoria.logs.sigaint.au
    - victoria.ts.sigaint.au
  issuerRef:
    name: le-production
    kind: ClusterIssuer