apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sigaint-monitoring
resources:
  - ../../base
  - networkpolicy.yaml
patches:
  - target:
      kind: Certificate
      name: victoria-logs-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: "observe.sigaint.au"
      - op: replace
        path: /spec/dnsNames
        value:
          - observe.sigaint.au
      - op: replace
        path: /spec/issuerRef/name
        value: le-production
