apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
  namespace: sigaint-applications
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretName: homepage-tls
  commonName: __PATCH__
  dnsNames:
    - __PATCH__
  issuerRef:
    name: __PATCH__
    kind: ClusterIssuer
