apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: homepage
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: homepage
  repo: oci://tccr.io/truecharts/

patches:
  - target:
      kind: Deployment
      name: homepage
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/securityContext
        value: {}
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value: {}
      - op: replace
        path: /spec/template/spec/securityContext
        value: {}
      - op: replace
        path: /spec/securityContext
        value: {}
