apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: homepage
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: homepage
  repo: https://jameswynn.github.io/helm-charts