kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-https
  namespace: external-secrets
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - external-secrets
  egress:
    - ports:
        - protocol: TCP
          port: 443
      to: []
  policyTypes:
    - Egress
