apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mgmt-lhm-prod.yaml
  - secure-lhm-prod.yaml
  - security-lhm-prod.yaml
  - user-lhm-prod.yaml
  - server-lhm-prod.yaml
  - dmz-lhm-prod.yaml
  - vmnet-lhm-prod.yaml
  - dhcp-shim.yaml
