apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
  name: net-sigaint-dmz
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "net-sigaint-dmz",
        "type": "bridge",
        "bridge": "br1",
        "ipam": {
          "type": "whereabouts",
          "range": "10.120.20.0/24",
          "range_start": "10.120.20.10",
          "range_end": "10.120.20.50"
        },
        "macspoofchk": false,
        "preserveDefaultVlan": false,
        "vlan": 20
    }
