apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
  name: net-sigaint-vmnet
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "net-sigaint-dmz",
        "type": "bridge",
        "bridge": "br1",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false,
        "vlan": 21
    }
