apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net-sigaint-vmnet
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "net-sigaint-vmnet",
      "type": "bridge",
      "bridge": "br1",
      "disableContainerInterface": true,
      "macspoofchk": false,
      "preserveDefaultVlan": false,
      "vlan": 21
    }
