apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
  name: net-sigaint-wifi
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "net-sigaint-wifi",
        "type": "bridge",
        "bridge": "br1",
        "ipam": {
           "type": "whereabouts",
          "range": "10.120.13.0/24",
          "range_start": "10.120.13.10",
          "range_end": "10.120.13.50"
        },
        "macspoofchk": true,
        "preserveDefaultVlan": false,
        "vlan": 13
    }
