apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net-sigaint-corp
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "net-sigaint-corp",
      "type": "macvlan",
      "master": "bond1.13",
        "ipam": {
          "type": "dhcp"
        },
        "macspoofchk": false,
        "preserveDefaultVlan": false,
        "vlan": 13
    }
