apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net-sigaint-wifi
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "net-sigaint-wifi",
      "type": "macvlan",
      "master": "bond1.13",
        "ipam": {
          "type": "whereabouts",
          "range": "10.120.13.0/24",
          "range_start": "10.120.13.10",
          "range_end": "10.120.13.50"
        },
        "macspoofchk": false,
        "preserveDefaultVlan": false,
        "vlan": 13
    }
