apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net-sigaint-corp
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "net-sigaint-corp",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "vlanID": 13,
      "mtu": 1500,
      "netAttachDefName": "default/net-sigaint-corp"
    }
