apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: lan-gws-01.dmz.sigaint.au
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: centos-stream9-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.29.2
  name: lan-gws-01.dmz.sigaint.au
  namespace: sigaint-dmz
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: lan-gws-01.dmz.sigaint.au
      spec:
        sourceRef:
          kind: DataSource
          name: freebsd-14.1
          namespace: sigaint-dmz
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: centos-stream9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: lan-gws-01.dmz.sigaint.au
        kubevirt.io/size: small
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: sk-lan-local
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              macAddress: 'ae:9d:22:e3:aa:f6'
              model: virtio
              name: nic-sigaint-dmz
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 8Gi
        resources: {}
      networks:
        - multus:
            networkName: default/net-sigaint-dmz
          name: nic-sigaint-dmz
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: lan-gws-01.dmz.sigaint.au
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
              password: TEL3HokWipEK7yNOciHaDAL-AHAR
              chpasswd: { expire: False }
          name: cloudinitdisk
