---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: physnet1-external-eno4
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            multicast-snooping: true
            stp:
              enabled: false
          port:
            - name: eno4
        description: External Networks
        ipv4:
          dhcp: true
          enabled: true
        name: br1
        state: up
        type: linux-bridge
  nodeSelector:
    sigaint.au/physnet: eno4