apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: physnet-eno4-br1
spec:
  desiredState:
    interfaces:
      - ipv4:
          dhcp: true
          enabled: true
        name: br1.20
        state: up
        type: vlan
        vlan:
          base-iface: br1
          id: 20
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: eno4
        description: External Networks
        ipv4:
          dhcp: true
          enabled: true
        name: br1
        state: up
        type: linux-bridge
  nodeSelector:
    sigaint.au/physnet: eno4