---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: physnet1-external-eno2
spec:
  desiredState:
    interfaces:
      - bridge:
          allow-extra-patch-ports: true
          options:
            mcast-snooping-enable: true
            stp: false
          port:
            - name: eno2
        name: ovs-br1
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: ovs-br1
          localnet: net-sigaint-corp
          state: present
        - bridge: ovs-br1
          localnet: net-sigaint-dmz
          state: present
        - bridge: ovs-br1
          localnet: net-sigaint-vmnet
          state: present
  nodeSelector:
    sigaint.au/physnet: eno2