apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: physnet-eno4-br1
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: eno4
        description: External Networks
        ipv4:
          enabled: false
        name: br1
        state: up
        type: linux-bridge
  nodeSelector:
    sigaint.au/physnet: eno4