---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
spec:
  managementState: Managed
  size: 1x.small
  storage:
    schemas:
      - effectiveDate: '2025-10-05'
        version: v13
    secret:
      name: loki-s3 # sigaint-monitoring-loki-s3
      type: s3
    tls:
      caKey: service-ca.crt
      caName: openshift-service-ca.crt
  storageClassName: ocs-storagecluster-ceph-rbd
  tenants:
    mode: openshift-logging
