---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: le-staging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging-issuer-account-key
    solvers:
      # idm-459f.de.sigaint.au
      - dns01:
          rfc2136:
            nameserver: 51.75.64.48:53
            tsigKeyName: cert-manager
            tsigAlgorithm: HMACSHA256
            tsigSecretSecretRef:
              name: tsig-secret
              key: tsig-secret

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: le-production
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-production-issuer-account-key
    solvers:
      # idm-459f.de.sigaint.au
      - dns01:
          rfc2136:
            nameserver: 51.75.64.48:53
            tsigKeyName: cert-manager
            tsigAlgorithm: HMACSHA256
            tsigSecretSecretRef:
              name: tsig-secret
              key: tsig-secret
