apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: '15'
resources:
  - https://github.com/redhat-cop/gitops-catalog/nmstate/instance/overlays/default?ref=main