---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: Istio CNI
  name: istio-cni
---
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
spec:
  namespace: istio-cni
  profile: ambient