---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: Istio System
  name: istio-system
---
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  profile: ambient
  values:
    pilot:
      trustedZtunnelNamespace: ztunnel