apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: '-1'
namespace: metallb-system
resources:
  - namespace.yaml
  - subscription.yaml
  - operator-group.yaml