apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - node-1.osp.sigaint.au
              - node-2.osp.sigaint.au
              - node-3.osp.sigaint.au
              - node-4.osp.sigaint.au
              - node-5.osp.sigaint.au
              - node-6.osp.sigaint.au
  storageClassName: local-block
  volumeMode: Block
  deviceInclusionSpec:
    deviceTypes:
      - disk
    models:
      - 'RAID 930-8i-2GB'
      - 'PERC H730 Mini'