apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - node-1.osp.sigaint.au
              - node-2.osp.sigaint.au
              - node-3.osp.sigaint.au
              - node-4.osp.sigaint.au
              - node-5.osp.sigaint.au
              - node-6.osp.sigaint.au