apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    cluster.ocs.openshift.io/local-devices: "true"
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  flexibleScaling: true
  monDataDirHostPath: /var/lib/rook
  resourceProfile: lean
  encryption:
    keyRotation:
      schedule: '@weekly'
  managedResources:
    cephBlockPools:
      defaultStorageClass: true
  storageDeviceSets:
    - name: ocs-deviceset-local-block
      count: 6
      replica: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1"
          storageClassName: local-block
          volumeMode: Block
