apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-infrastructure
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: openshift-machine-config-operator
            wave: "-20"
          - name: openshift-cert-manager-operator
            wave: "-10"
          - name: openshift-external-secrets-operator
            wave: "-10"
          - name: lvm-storage
            wave: "-5"
          - name: openshift-ingress-operator
            wave: "0"
          - name: openshift-apiserver-operator
            wave: "0"
          - name: openshift-console-operator
            wave: "0"
          - name: openshift-logging-operator
            wave: "0"
          - name: advanced-cluster-management
            wave: "10"
  template:
    metadata:
      name: 'hub-{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/sigaint-au/sigaint-iac
        targetRevision: main
        path: 'infrastructure/{{.name}}/overlays/hub'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
