apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-infrastructure
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: openshift-machine-config-operator     # Done
      - name: openshift-cert-manager-operator       # X
      - name: openshift-external-secrets-operator   # X
      - name: lvm-storage                           # NEW
      - name: openshift-data-foundation-operator    # Done
      - name: openshift-ingress-operator            # Done
      - name: openshift-apiserver-operator          # Done
      - name: openshift-console-operator            # Done
      - name: openshift-logging-operator            # Done
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/sigaint-au/sigaint-iac
        targetRevision: HEAD
        path: 'infrastructure/{{.name}}/overlays/hub/'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
