apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# Annotate common cluster config kinds for Server-Side Apply via Argo CD.
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true,RespectIgnoreDifferences=true
