apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-infrastructure
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: openshift-machine-config-operator
      - name: openshift-cert-manager-operator
      - name: external-secrets-operator
      - name: local-storage
      - name: openshift-data-foundation-operator
      - name: nmstate
      - name: virtualization-operator
      - name: openshift-ingress-operator
      - name: openshift-apiserver-operator
      - name: openshift-console-operator
      - name: openshift-pipelines-operator
      - name: metallb-operator
      - name: crunchy-postgres-operator
      - name: cloudnative-pg-operator
      - name: quay-operator
      - name: tailscale
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/sigaint-au/sigaint-iac
        targetRevision: HEAD
        path: 'infrastructure/{{.name}}/overlays/ocp/'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
