apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-virtualization
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: namespaces
            wave: "30"
          - name: access-credentials
            wave: "35"
          - name: network-attachment-definitions
            wave: "35"
  template:
    metadata:
      name: 'virt-{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.wave}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: virtualization
      source:
        repoURL: https://github.com/sigaint-au/sigaint-iac
        targetRevision: main
        path: 'virtualization/{{.name}}/overlays/ocp'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
