apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-virtualization
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: namespaces
      - name: access-credentials
      - name: tailscale-router
      - name: freeipa-server
      - name: network-attachment-definitions
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "virtualization"
      source:
        repoURL: https://github.com/sigaint-au/sigaint-iac
        targetRevision: HEAD
        path: 'virtualization/{{.name}}/overlays/ocp/'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true