apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: ocp
  namespace: infra-hosting
spec:
  baseDomain: sigaint.au
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: ocp
    version: v1beta1
  clusterName: ocp

  controlPlane:
    replicas: 3

  # This is the required addition
  platform:
    agentBareMetal:
      agentSelector: {}               # ← empty = any agent is allowed

  pullSecretRef:
    name: pullsecret-infra-hosting

  installed: false