# Dell / eno3 group

apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-ocp-node-ab56
  namespace: infra-hosting
  labels:
    infraenv: infra-hosting
spec:
  interfaces:
    - name: eno3
      macAddress: 44:a8:42:0a:5e:e7
    - name: eno4
      macAddress: 44:a8:42:0a:5e:e9
  config:
    interfaces:
      - name: eno3
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
      - name: eno4
        type: ethernet
        state: down
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    dns-resolver:
      config:
        server:
          - 9.9.9.9
          - 149.112.112.112
    routes:
      config: []

---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-ocp-node-527f
  namespace: infra-hosting
  labels:
    infraenv: infra-hosting
spec:
  interfaces:
    - name: eno3
      macAddress: 80:18:44:ec:23:e6
    - name: eno4
      macAddress: 80:18:44:ec:23:e7
  config:
    interfaces:
      - name: eno3
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
      - name: eno4
        type: ethernet
        state: down
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    dns-resolver:
      config:
        server:
          - 9.9.9.9
          - 149.112.112.112
    routes:
      config: []

---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-ocp-node-49f4
  namespace: infra-hosting
  labels:
    infraenv: infra-hosting
spec:
  interfaces:
    - name: eno3
      macAddress: 18:66:da:ef:6d:8a
    - name: eno4
      macAddress: 18:66:da:ef:6d:8b
  config:
    interfaces:
      - name: eno3
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
      - name: eno4
        type: ethernet
        state: down
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    dns-resolver:
      config:
        server:
          - 9.9.9.9
          - 149.112.112.112
    routes:
      config: []

---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-ocp-node-8f1c
  namespace: infra-hosting
  labels:
    infraenv: infra-hosting
spec:
  interfaces:
    - name: eno3
      macAddress: 18:66:da:ef:7d:aa
    - name: eno4
      macAddress: 18:66:da:ef:7d:ab
  config:
    interfaces:
      - name: eno3
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
      - name: eno4
        type: ethernet
        state: down
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    dns-resolver:
      config:
        server:
          - 9.9.9.9
          - 149.112.112.112
    routes:
      config: []

---
# Lenovo / eno2 group

apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-ocp-node-55f9
  namespace: infra-hosting
  labels:
    infraenv: infra-hosting
spec:
  interfaces:
    - name: eno1np0
      macAddress: 7c:d3:0a:59:3f:90
    - name: eno2np1
      macAddress: 7c:d3:0a:59:3f:91
  config:
    interfaces:
      - name: eno1np0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
      - name: eno2np1
        type: ethernet
        state: down
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    dns-resolver:
      config:
        server:
          - 9.9.9.9
          - 149.112.112.112
    routes:
      config: []

---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: nmstate-ocp-node-9e4a
  namespace: infra-hosting
  labels:
    infraenv: infra-hosting
spec:
  interfaces:
    - name: eno1np0
      macAddress: 38:68:dd:05:7e:d8
    - name: eno2np1
      macAddress: 38:68:dd:05:7e:d9
  config:
    interfaces:
      - name: eno1np0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
      - name: eno2np1
        type: ethernet
        state: down
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    dns-resolver:
      config:
        server:
          - 9.9.9.9
          - 149.112.112.112
    routes:
      config: []