apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-operator
spec:
  channel: "__PATCH__"
  installPlanApproval: Automatic
  name: kiali-ossm
  source: redhat-operators
  sourceNamespace: kiali-operator
