apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sigaint-monitoring
resources:
  - ../../base
patches:
    # Patch certificate names and issuerR`
  - target:
      kind: Certificate
      name: victoria-metrics-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: "metrics.sigaint.au"
      - op: replace
        path: /spec/dnsNames
        value:
          - metrics.sigaint.au
          - metrics.ts.sigaint.au
      - op: replace
        path: /spec/issuerRef/name
        value: le-production
