---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-sk-lan-local
  namespace: sigaint-vmnet
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: sk-lan-local
  data:
    - secretKey: key
      remoteRef:
        key: SSH_PUBKEY_LAN_LOCAL