---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-sk-lan-local
  namespace: sigaint-vmnet
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: sk-lan-local
  data:
    - secretKey: key
      remoteRef:
        key: SSH_PUBKEY_LAN_LOCAL
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
