apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-tls.yaml
helmCharts:
- name: victoria-metrics-single
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: victoria-metrics
  repo: https://victoriametrics.github.io/helm-charts/