kind: Service
apiVersion: v1
metadata:
  name: victoria-metrics-ingest
  namespace: sigaint-monitoring
  labels:
    app: server
  annotations:
    metallb.io/ip-allocated-from-pool: net-sigaint-dmz
    metallb.universe.tf/address-pool: net-sigaint-dmz
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: http
      protocol: TCP
      port: 8428
      targetPort: http
      nodePort: 30199
  internalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  sessionAffinity: None
  selector:
    app: server
    app.kubernetes.io/name: victoria-metrics-single